import { promises as fs } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CONTRACT_NAME = 'TerraTempoCore';
const HARDHAT_DEPLOYMENTS_PATH = join(__dirname, '../../fhevm-hardhat-template/deployments');
const OUTPUT_DIR = join(__dirname, '../abi');

async function generateABI() {
  try {
    // Ensure output directory exists
    await fs.mkdir(OUTPUT_DIR, { recursive: true });

    // Read contract ABI from deployments
    const networks = ['localhost'];
    const addresses = {};
    let abi = null;

    for (const network of networks) {
      try {
        const deploymentPath = join(HARDHAT_DEPLOYMENTS_PATH, network, `${CONTRACT_NAME}.json`);
        const deploymentData = JSON.parse(await fs.readFile(deploymentPath, 'utf-8'));
        
        if (!abi) {
          abi = deploymentData.abi;
        }
        
        addresses[network] = deploymentData.address;
        console.log(`✓ Found ${CONTRACT_NAME} on ${network}: ${deploymentData.address}`);
      } catch (error) {
        console.log(`⚠ ${network} deployment not found, skipping...`);
      }
    }

    if (!abi) {
      console.error(`✗ No ABI found for ${CONTRACT_NAME}`);
      console.log('Please deploy the contract first:');
      console.log('  cd fhevm-hardhat-template');
      console.log('  npx hardhat node (in separate terminal)');
      console.log('  npx hardhat deploy --network localhost');
      process.exit(1);
    }

    // Generate ABI file
    const abiContent = `// Auto-generated by genabi.mjs
// Do not edit manually

export const ${CONTRACT_NAME}ABI = ${JSON.stringify(abi, null, 2)} as const;
`;

    await fs.writeFile(join(OUTPUT_DIR, `${CONTRACT_NAME}ABI.ts`), abiContent, 'utf-8');
    console.log(`✓ Generated ${CONTRACT_NAME}ABI.ts`);

    // Generate addresses file
    const addressesContent = `// Auto-generated by genabi.mjs
// Do not edit manually

export const ${CONTRACT_NAME}Addresses = ${JSON.stringify(addresses, null, 2)} as const;

export function get${CONTRACT_NAME}Address(network: string): string | undefined {
  return ${CONTRACT_NAME}Addresses[network as keyof typeof ${CONTRACT_NAME}Addresses];
}
`;

    await fs.writeFile(join(OUTPUT_DIR, `${CONTRACT_NAME}Addresses.ts`), addressesContent, 'utf-8');
    console.log(`✓ Generated ${CONTRACT_NAME}Addresses.ts`);

    console.log('\n✓ ABI generation completed successfully!');
  } catch (error) {
    console.error('✗ Error generating ABI:', error.message);
    process.exit(1);
  }
}

generateABI();


