// Auto-generated by genabi.mjs
// Do not edit manually

export const TerraTempoCoreAddresses = {
  "localhost": "0x25a0c696b1f97816123b3fEfB5d1F2C578BA28c7",
  "sepolia": "0x8A0D184b6f829E3dbfBbb6459D206358F078ceBe"
} as const;

export function getTerraTempoCoreAddress(network: string): string | undefined {
  return TerraTempoCoreAddresses[network as keyof typeof TerraTempoCoreAddresses];
}
